apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  containers:
    - name: node-web-app
      image: rajashekarjangam/node-docker-web-app:latest
      ports:
        - containerPort: 8080
